INSERT INTO DWorksAt (DocIDNo, HospIDNo)
VALUES (101, 1);
INSERT INTO DWorksAt (DocIDNo, HospIDNo)
VALUES (562, 1);
INSERT INTO DWorksAt (DocIDNo, HospIDNo)
VALUES (343, 2);
INSERT INTO DWorksAt (DocIDNo, HospIDNo)
VALUES (764, 3);
INSERT INTO DWorksAt (DocIDNo, HospIDNo)
VALUES (115, 3);
INSERT INTO DWorksAt (DocIDNo, HospIDNo)
VALUES (906, 3);
INSERT INTO DWorksAt (DocIDNo, HospIDNo)
VALUES (67, 2);
INSERT INTO DWorksAt (DocIDNo, HospIDNo)
VALUES (418, 1);
INSERT INTO DWorksAt (DocIDNo, HospIDNo)
VALUES (99, 2);
